#!/bin/bash
#$ -pe smp 8
#$ -N long
#$ -q fig_1

module load gcc
module load gsl

# proof-of-concept network with 10% local and 90% imported
../src/main.out ../../data/figs/fig_1/10local_90imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_travel.csv ../../data/figs/fig_1/10local_90imported/space_time_travel/networks_0.csv ../../data/figs/fig_1/10local_90imported/space_time_travel/scalars_0.csv ../../data/figs/fig_1/10local_90imported/space_time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/10local_90imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_bth.csv ../../data/figs/fig_1/10local_90imported/space_time_bth/networks_0.csv ../../data/figs/fig_1/10local_90imported/space_time_bth/scalars_0.csv ../../data/figs/fig_1/10local_90imported/space_time_bth/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/10local_90imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time.csv ../../data/figs/fig_1/10local_90imported/space_time/networks_0.csv ../../data/figs/fig_1/10local_90imported/space_time/scalars_0.csv ../../data/figs/fig_1/10local_90imported/space_time/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/10local_90imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_travel.csv ../../data/figs/fig_1/10local_90imported/time_travel/networks_0.csv ../../data/figs/fig_1/10local_90imported/time_travel/scalars_0.csv ../../data/figs/fig_1/10local_90imported/time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/10local_90imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_bth.csv ../../data/figs/fig_1/10local_90imported/time_bth/networks_0.csv ../../data/figs/fig_1/10local_90imported/time_bth/scalars_0.csv ../../data/figs/fig_1/10local_90imported/time_bth/swaps_0.csv 123

# proof-of-concept network with 50% local and 50% imported
../src/main.out ../../data/figs/fig_1/50local_50imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_travel.csv ../../data/figs/fig_1/50local_50imported/space_time_travel/networks_0.csv ../../data/figs/fig_1/50local_50imported/space_time_travel/scalars_0.csv ../../data/figs/fig_1/50local_50imported/space_time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/50local_50imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_bth.csv ../../data/figs/fig_1/50local_50imported/space_time_bth/networks_0.csv ../../data/figs/fig_1/50local_50imported/space_time_bth/scalars_0.csv ../../data/figs/fig_1/50local_50imported/space_time_bth/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/50local_50imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time.csv ../../data/figs/fig_1/50local_50imported/space_time/networks_0.csv ../../data/figs/fig_1/50local_50imported/space_time/scalars_0.csv ../../data/figs/fig_1/50local_50imported/space_time/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/50local_50imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_travel.csv ../../data/figs/fig_1/50local_50imported/time_travel/networks_0.csv ../../data/figs/fig_1/50local_50imported/time_travel/scalars_0.csv ../../data/figs/fig_1/50local_50imported/time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/50local_50imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_bth.csv ../../data/figs/fig_1/50local_50imported/time_bth/networks_0.csv ../../data/figs/fig_1/50local_50imported/time_bth/scalars_0.csv ../../data/figs/fig_1/50local_50imported/time_bth/swaps_0.csv 123

# proof-of-concept network with 95% local and 05% imported
../src/main.out ../../data/figs/fig_1/95local_05imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_travel.csv ../../data/figs/fig_1/95local_05imported/space_time_travel/networks_0.csv ../../data/figs/fig_1/95local_05imported/space_time_travel/scalars_0.csv ../../data/figs/fig_1/95local_05imported/space_time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/95local_05imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time_bth.csv ../../data/figs/fig_1/95local_05imported/space_time_bth/networks_0.csv ../../data/figs/fig_1/95local_05imported/space_time_bth/scalars_0.csv ../../data/figs/fig_1/95local_05imported/space_time_bth/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/95local_05imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_space_time.csv ../../data/figs/fig_1/95local_05imported/space_time/networks_0.csv ../../data/figs/fig_1/95local_05imported/space_time/scalars_0.csv ../../data/figs/fig_1/95local_05imported/space_time/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/95local_05imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_travel.csv ../../data/figs/fig_1/95local_05imported/time_travel/networks_0.csv ../../data/figs/fig_1/95local_05imported/time_travel/scalars_0.csv ../../data/figs/fig_1/95local_05imported/time_travel/swaps_0.csv 123
../src/main.out ../../data/figs/fig_1/95local_05imported/nodes_1_FULL_adjusted.csv ../../data/network_sim/sources_NULL.csv ../../data/network_sim/settings_time_bth.csv ../../data/figs/fig_1/95local_05imported/time_bth/networks_0.csv ../../data/figs/fig_1/95local_05imported/time_bth/scalars_0.csv ../../data/figs/fig_1/95local_05imported/time_bth/swaps_0.csv 123
